name: Update Profile Progress [ ▣_▣ ]

on:
  push:
    branches:
      - main
    paths:
      - "progress.json"
      - ".github/workflows/update-progress.yml"
      - "profile/README.md"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README progress
        run: |
          TABLE=$(jq -r '
            def s: if .>=100 then "Stable" elif .>=76 then "Polishing" elif .>=51 then "Experimental" elif .>=31 then "Alpha" elif .>=11 then "Development" else "Planning" end;
            "| Project | Progress | Status |\n| :--- | :--- | :--- |",
            (to_entries[] | "| [**\(.value.name)**](\(.value.url)) | `\(.value.percent)%` | `\(.value.percent | s)` |")' progress.json)
          perl -i -0777 -pe "s{(<!-- roadmap_table -->\n).*?(\n<!-- roadmap_table_end -->)}{\$1$TABLE\$2}s" profile/README.md

      - name: Commit and Push
        run: |
          git config --global user.name "robonanoo"
          git config --global user.email "bot@nanoolabs.dev"
          git add profile/README.md
          git diff --staged --quiet || git commit -m "chore: auto-update project progress nanoolabs"
          git push
